### ISSUE TITLE
Table djangocms_googlemap_googlemap doesn't exist

### ISSUE THREAD

**Issue by jbouvier** [divio/djangocms-googlemap#4]
I'm attempting to upgrade from cms 2.4 and am getting this error when running migrations for the new djangocms-googlemap app:
`DatabaseError: (1146, "Table 'madison.djangocms_googlemap_googlemap' doesn't exist")`

Full traceback:

```
Running migrations for djangocms_googlemap:
 - Migrating forwards to 0001_initial.
 > djangocms_googlemap:0001_initial
FailedDryRun:  ! Error found during dry run of '0001_initial'! Aborting.
Traceback (most recent call last):
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 173, in _run_migration
    migration_function()
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/south/migration/migrators.py", line 62, in <lambda>
    return (lambda: direction(orm))
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/djangocms_googlemap/migrations/0001_initial.py", line 23, in forwards
    description = connection.introspection.get_table_description(connection.cursor(), 'djangocms_googlemap_googlemap')
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/django/db/backends/mysql/introspection.py", line 49, in get_table_description
    cursor.execute("SELECT * FROM %s LIMIT 1" % self.connection.ops.quote_name(table_name))
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 130, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 120, in execute
    return self.cursor.execute(query, args)
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/jordan/Development/madison/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
DatabaseError: (1146, "Table 'madison.djangocms_googlemap_googlemap' doesn't exist")
```

**Comment by FinalAngel** [comment]
please upgrade to the latest version and reopen if the issue still persists.
