### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sstephans** [divio/djangocms-googlemap#82]
I'm trying to install via putty and, after succesfully running the pip install and adding 'djangocms-googlemap', to the list in mysite/settings.py, I run 

> python manage.py migrate djangocms_googlemap

and get the following:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/root/treesite/myvenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/root/treesite/myvenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/root/treesite/myvenv/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/root/treesite/myvenv/lib/python3.5/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/root/treesite/myvenv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'djangocms_googlemap'

```

**Comment by FinalAngel** [comment]
@sstephans you need to add "djangocms_googlemap" to INSTALLED_APPS not "djangocms-googlemap".

**Comment by sstephans** [comment]
Ah, apologies, that was a typo in my comment. I copied and pasted from the page, and double-checking it is djangocms_googlemap in settings.py.

I just realized (sorry, total noob here) that CMS is a thing of its own I need to install. So I'm going to try installing all that and see if it resolves the maps issue.
